name: pub_semver
version: 1.1.0-dev
author: Dart Team <misc@dartlang.org>
description: >
 Versions and version constraints implementing pub's versioning policy. This
 is very similar to vanilla semver, with a few corner cases.
homepage: http://github.com/dart-lang/pub_semver
dependencies:
  collection: ">=0.9.0 <2.0.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.12.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
